services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "${HOST_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  prod:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
